config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # some below blog post can be handled in resources direct
  # resources :blog_posts

  get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  post "/blog_posts", to: "blog_posts#create", as: :blog_posts

  # both below does the smae
  post "/blog_posts/update/:id", to: "blog_posts#update"
  patch "/blog_posts/:id", to: "blog_posts#update", as: :update_blog_posts

  # both below does the same
  post "/blog_posts/:id/delete", to: "blog_posts#delete"
  delete "/blog_posts/:id", to: "blog_posts#delete", as: :delete_post

  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true

  scope :sorted, -> {order(published_at: :desc)}
  scope :draft, -> {where(published_at: nil)}
  scope :published, -> {where("published_at <= ?", Time.current)}
  scope :scheduled, -> {where("published_at > ?", Time.current)}

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  before_action :get_post_by_user, only: []
  before_action :set_blog_post_by_id, only: [:show, :edit, :delete, :update]
  before_action :authenticate_user!, except: [:index, :show]



  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted.all.where(user_id: current_user.id) : BlogPost.published.sorted
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_allowed_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :bad_request
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_allowed_params)
      redirect_to @blog_post
    else
      render :edit, status: :bad_request
    end
  end

  def delete
    if @blog_post.destroy
      redirect_to root_path
    else
      render :show, status: :bad_request
    end
  end

  private

  def blog_post_allowed_params
    params.require(:blog_post).permit(:title, :body, :published_at, :user_id)
  end

  def set_blog_post_by_id
  # if params[:user_id] != current_user.id
  #     redirect_to root_path
  # end
  @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/edit.html.erb
<h2>New Blog</h2>
<%= form_with(model: @blog_post, method: :patch) do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>

    <div>
        <%= form.label :published_at %>
        <%= form.datetime_select :published_at, include_blank: true %>
    </div>
    <%= form.button %>
<% end %>

app/views/blog_posts/index.html.erb
<h2>
Hello, Welcome to my blog!
</h2>
<h4>

</h4>

<div>
    <% @blog_posts.each do |value| %>
    <div>
       <%= link_to value.title, blog_post_path(value) %> 
        <% if value.draft? %> <span>draft </span><% end %>
        <% if value.scheduled? %> <span>scheduled</span> <% end %>
        <% if value.published? %> <span>published</span> <% end %>

    </div>
    <% end %>

</div>

app/views/blog_posts/new.html.erb
<h2>New post</h2>



<%= form_with model: @blog_post do |form| %>

    <% if @blog_post.errors.full_messages.any? %>
        <% @blog_post.errors.full_messages do |msg| %>
            <h3><%= msg %></h3>
        <% end %>
    <% end %>  

 
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>
    <div>
        <%= form.label :published_at %>
        <%= form.datetime_select :published_at, include_blank: true %>
    </div>
    <div>
        <%= form.hidden_field :user_id, value: current_user.id %>
    </div>  
    <%= form.button %>
<% end %>

app/views/blog_posts/show.html.erb
<div>
    <h2><%= @blog_post.title %> </h2>
    <p><%= @blog_post.body %> <p>
    <% if user_signed_in? %>
    <%= button_to "edit", edit_blog_post_path, method: :get %>
    <%= button_to "delete", "/blog_posts/#{@blog_post.id}/delete", data: { turbo_method: :post, turbo_confirm: "Are you sure??" } %>
    <% #= button_to "delete", @blog_post, method: :delete %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

        
      <%= link_to "Home", root_path %>
       <% if user_signed_in? %>
          <%= link_to "Profile", edit_user_registration_path %>
          <%= link_to "create post", new_blog_post_path %> 
          <%= button_to "Logout", destroy_user_session_path, method: :delete %>
       <% end %>
       <% if !user_signed_in? %>
          <%= link_to "Login", new_user_session_path %>

       <% end %>
    <%= yield %>
  </body>
</html>